var Question = Spine.Model.setup(
    "Question",
    [
        "id",
        "num",
        "type",
        "text",
        "low_text",
        "high_text",
        "lat",
        "lng",
        "zoom",
		"choice1",
		"choice2",
		"choice3",
		"choice4",
		"choice5",
		"choice6",
		"choice7",
		"choice8",
		"otherchoice",
        "answer_location",
        "answer_visible",
        "comments",
        "map_type"
    ]
);
